on:
  push:
    tags:
      - 'v*'

name: Release
jobs:
  publish:
      permissions:
        contents: write
      name: ${{ matrix.name }} (${{ matrix.target }})
      runs-on: ${{ matrix.os }}
      strategy:
        fail-fast: false
        matrix:
          target:
            - x86_64-unknown-linux-gnu
            - x86_64-unknown-linux-musl
            - x86_64-apple-darwin
            - x86_64-unknown-freebsd
            - aarch64-apple-darwin
            - aarch64-linux-android
            - aarch64-unknown-linux-musl
            - armv7-unknown-linux-gnueabihf
  
          include:
            - os: ubuntu-latest
              name: Linux GNU x86_64
              target: x86_64-unknown-linux-gnu
              artifact_name: target/x86_64-unknown-linux-gnu/release/fetchrs
              release_name: fetchrs-linux-gnu-x86_64.tar.gz
              cross: false
              strip: true
  
            - os: ubuntu-latest
              name: Linux musl x86_64
              target: x86_64-unknown-linux-musl
              artifact_name: target/x86_64-unknown-linux-musl/release/fetchrs
              release_name: fetchrs-linux-musl-x86_64.tar.gz
              cross: true
              strip: true
  
            - os: macos-latest
              name: macOS x86_64
              target: x86_64-apple-darwin
              artifact_name: target/x86_64-apple-darwin/release/fetchrs
              release_name: fetchrs-macos-x86_64.tar.gz
              cross: false
              strip: true
  
            - os: macos-latest
              name: macOS aarch64
              target: aarch64-apple-darwin
              artifact_name: target/aarch64-apple-darwin/release/fetchrs
              release_name: fetchrs-macos-aarch64.tar.gz
              cross: false
              strip: true
  
            - os: ubuntu-latest
              name: freeBSD x86_64
              target: x86_64-unknown-freebsd
              artifact_name: target/x86_64-unknown-freebsd/release/fetchrs
              release_name: fetchrs-freebsd-x86_64.tar.gz
              cross: true
              strip: true
  
            - os: ubuntu-latest
              name: Android
              target: aarch64-linux-android
              artifact_name: target/aarch64-linux-android/release/fetchrs
              release_name: fetchrs-android-aarch64.tar.gz
              cross: true
              strip: true
  
            - os: ubuntu-latest
              name: Linux musl aarch64
              target: aarch64-unknown-linux-musl
              artifact_name: target/aarch64-unknown-linux-musl/release/fetchrs
              release_name: fetchrs-linux-musl-aarch64.tar.gz
              cross: true
              strip: true
  
            - os: ubuntu-latest
              name: Linux ARMv7
              target: armv7-unknown-linux-gnueabihf
              artifact_name: target/armv7-unknown-linux-gnueabihf/release/fetchrs
              release_name: fetchrs-linux-gnueabihf-armv7.tar.gz
              cross: true
              strip: true
  
      steps:
        - name: Checkout
          uses: actions/checkout@v2
  
        - name: Bootstrap
          uses: actions-rs/toolchain@v1
          with:
            toolchain: stable
            target: ${{ matrix.target }}
  
        - name: Build
          uses: actions-rs/cargo@v1
          with:
            command: build
            args: --target=${{ matrix.target }} --release
            use-cross: ${{ matrix.cross }}
  
        - name: Compress binaries
          run: if [ "$RUNNER_OS" != "Windows" ]; then
              tar cfzv ${{ matrix.release_name }} -C "$(dirname ${{ matrix.artifact_name}})" "$(basename ${{ matrix.artifact_name }})";
            else
              mv ${{ matrix.artifact_name }} ${{ matrix.release_name }};
            fi
          shell: bash
  
        - name: Upload binaries
          uses: softprops/action-gh-release@v1
          with:
            files: ${{ matrix.release_name }}
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
